blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, \
    ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(30)(ArticleListView.as_view()), name='list'),
    path('view/<int:pk>/', ArticleDetailView.as_view(), name='view'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

mailings/urls.py
from django.urls import path
from .apps import MailingsConfig
from .views import IndexView, ContactFormView, MessageCreateView, \
    MessageListView, MessageDeleteView, MessageUpdateView, \
    MailSettingsListView, MailSettingsCreateView, MailSettingsUpdateView, \
    MailSettingsDeleteView, \
    StatusMailingSettingsUpdateView, MailingLogListView, ClientListView, \
    ClientCreateView, ClientUpdateView, \
    ClientDeleteView

app_name = MailingsConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('contacts/', ContactFormView.as_view(), name='contacts'),

    path('message/create', MessageCreateView.as_view(), name='message_create'),
    path('message/list', MessageListView.as_view(), name='message_list'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(),
         name='message_delete'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(),
         name='message_update'),

    path('list/', MailSettingsListView.as_view(), name='list'),
    path('create/', MailSettingsCreateView.as_view(), name='create'),
    path('update/<int:pk>', MailSettingsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', MailSettingsDeleteView.as_view(), name='delete'),

    path('status_update/<int:pk>/', StatusMailingSettingsUpdateView.as_view(),
         name='status_update'),

    path('mailing_log/<int:pk>/', MailingLogListView.as_view(),
         name='mail_log'),

    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(),
         name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(),
         name='client_delete'),
]

mailings/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    first_name = models.CharField(max_length=100, **NULLABLE,
                                  verbose_name='фамилия')
    last_name = models.CharField(max_length=100, **NULLABLE,
                                 verbose_name='имя')
    surname = models.CharField(max_length=100, **NULLABLE,
                               verbose_name='отчество')
    email = models.EmailField(max_length=100, verbose_name='email')
    comment = models.TextField(blank=True, verbose_name='комментарий')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, **NULLABLE,
                             related_name='create_client',
                             verbose_name='добавил клиента')

    def __str__(self):
        return (f'{self.first_name} {self.last_name} {self.surname} -'
                f' {self.email}')

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class MailSettings(models.Model):
    STATUS_CREATED = 'created'
    STATUS_IN_PROCESS = 'in_process'
    STATUS_FINISHED = 'finished'

    STATUSES = (
        (STATUS_CREATED, 'Создано'),
        (STATUS_IN_PROCESS, 'В процессе'),
        (STATUS_FINISHED, 'Завершена'),
    )

    PERIOD_DAILY = 'day'
    PERIOD_WEEKLY = 'week'
    PERIOD_MONTHLY = 'month'

    PERIOD_CHOICES = (
        ('day', 'Раз в день'), ('week', 'Раз в неделю'),
        ('month', 'Раз в месяц'))
    STATUS_CHOICES = (('create', 'Создана'), ('in_process', 'Запущена'),
                      ('finished', 'Завершена'))

    message = models.ForeignKey('Message', on_delete=models.CASCADE,
                                verbose_name='Сообщение')
    start_time = models.DateTimeField(verbose_name='Время начала рассылки')
    end_time = models.DateTimeField(verbose_name='Время окончания', **NULLABLE)
    period = models.CharField(max_length=50, choices=PERIOD_CHOICES,
                              verbose_name='Периодичность рассылки')
    client = models.ManyToManyField(Client, related_name="get_client",
                                    verbose_name='Клиент')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES,
                              default='in_process', verbose_name='Статус '
                                                                 'рассылки')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, **NULLABLE,
                             related_name='create_mail',
                             verbose_name='Добавил рассылку')

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [('set_status', 'Can deactivate mailings')]


class Message(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    message = models.TextField(**NULLABLE, verbose_name='сообщение')

    def __str__(self):
        return f'{self.title} ({self.message})'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Logs(models.Model):
    STATUS_SUCCESS = 'success'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_SUCCESS, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    last_try = models.DateTimeField(auto_now_add=True,
                                    verbose_name='дата последней попытки')
    status = models.CharField(choices=STATUSES, default=STATUS_SUCCESS,
                              verbose_name='статус')
    answer_server = models.TextField(verbose_name='ответ сервера', **NULLABLE)
    mailings = models.ForeignKey(MailSettings, on_delete=models.CASCADE,
                                 related_name="get_log",
                                 verbose_name='рассылка')

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailings/forms.py
from django import forms

from mailings.models import Message, Client, MailSettings


class FormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active' and field_name != 'client':
                field.widget.attrs['class'] = 'form-control'


class ContactForm(FormMixin, forms.Form):
    """
        Форма для контактов.
    """

    name = forms.CharField(label='Имя', max_length=255)
    email = forms.EmailField(label='Email')
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(
        attrs={'cols': 60, 'rows': 10}))


class MessageForm(FormMixin, forms.ModelForm):
    """
    Форма для создания и редактирования сообщения рассылки
    """

    class Meta:
        model = Message
        fields = '__all__'


class ClientForm(FormMixin, forms.ModelForm):
    """
    Форма для добавления и редактирования клиента
    """

    class Meta:
        model = Client
        exclude = ('user',)


class MailSettingsForm(FormMixin, forms.ModelForm):
    """
    Форма для создания и редактирования настроек рассылки.
    """

    class Meta:
        model = MailSettings
        exclude = ('user', 'status')
        help_texts = {'start_time': "Дата и время в формате: ДД.ММ.ГГГГ ЧЧ:ММ",
                      'end_time': "Дата и время в формате: ДД.ММ.ГГГГ ЧЧ:ММ",
                      }
        widgets = {
            'message': forms.Select,
            'client': forms.CheckboxSelectMultiple,
        }


class MailSettingsChangeStatus(FormMixin, forms.ModelForm):
    """
    Форма для изменения статуса рассылки
    """

    class Meta:
        model = MailSettings
        fields = ('status',)

mailings/views.py
from django.views.generic import ListView, UpdateView, DeleteView, \
    CreateView, TemplateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect, Http404

from mailings.forms import ContactForm, ClientForm, MailSettingsForm, \
    MailSettingsChangeStatus, MessageForm
from mailings.models import Client, MailSettings, Message, Logs
from mailings.services import my_job, get_cached_data, get_random_blog


class IndexView(TemplateView):
    """ Главная страница """

    template_name = 'mailings/index.html'

    def get_context_data(self):
        total_mailings_counter = get_cached_data()[0]
        active_mailings_counter = get_cached_data()[1]
        unique_client_counter = get_cached_data()[2]
        context = {
            'title': 'Главная',
            'total_mailings_counter': total_mailings_counter,
            'active_mailing_counter': active_mailings_counter,
            'unique_client_counter': unique_client_counter,
            'random_blog': get_random_blog() if get_random_blog() else [],
        }

        return context


class ContactFormView(FormView):
    """ Контактная информация и отправка сообщения """

    form_class = ContactForm
    template_name = 'mailings/contact.html'
    success_url = reverse_lazy('/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Свяжитесь с нами:'
        return context

    def form_valid(self, form):
        if form.is_valid():
            print(form.cleaned_data)
        return redirect('/')


###############################################################################
class ClientListView(LoginRequiredMixin, ListView):
    """ Список клиентов, доступны к просмотру клиенты, созданные
    пользователем"""

    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(user=self.request.user)

        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    """ Создание клиента """

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:clients')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирование клиента, доступны к редактированию клиенты, созданные
    пользователем"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:clients')

    def form_valid(self, form):
        if not self.request.user.is_staff:
            form.instance.user = self.request.user
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление клиента, доступны к удалению клиенты, созданные
    пользователем"""

    model = Client
    success_url = reverse_lazy('mailings:clients')


###############################################################################
class MailSettingsListView(LoginRequiredMixin, ListView):
    """ Список рассылок, созданных пользователем """

    model = MailSettings

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = super().get_queryset().filter(user=self.request.user)
        return queryset


class MailSettingsCreateView(LoginRequiredMixin, PermissionRequiredMixin,
                             CreateView):
    """ Создание рассылки """

    model = MailSettings
    form_class = MailSettingsForm
    permission_required = 'mailings.add_mailsettings'
    success_url = reverse_lazy('mailings:list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_superuser:
            form.fields['client'].queryset = Client.objects.filter(
                user=self.request.user)
        else:
            form.fields['client'].queryset = Client.objects.all()
        return form

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        my_job()

        return super().form_valid(form)


class MailSettingsUpdateView(LoginRequiredMixin, PermissionRequiredMixin,
                             UpdateView):
    """ Редактирование рассылки, доступны к редактированию рассылки,
    созданные пользователем"""

    model = MailSettings
    form_class = MailSettingsForm
    permission_required = 'mailings.change_mailsettings'
    success_url = reverse_lazy('mailings:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404

        return self.object


class MailSettingsDeleteView(LoginRequiredMixin, PermissionRequiredMixin,
                             DeleteView):
    """ Удаление рассылки """

    model = MailSettings
    permission_required = 'mailings.delete_mailsettings'
    success_url = reverse_lazy('mailings:list')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['clients'] = Client.objects.all()
        context_data['mail_pk'] = self.kwargs.get('pk')

        return context_data


class StatusMailingSettingsUpdateView(LoginRequiredMixin,
                                      PermissionRequiredMixin, UpdateView):
    model = MailSettings
    form_class = MailSettingsChangeStatus
    success_url = reverse_lazy('mailings:list')
    permission_required = 'mailings.set_status'


###############################################################################
class MessageListView(LoginRequiredMixin, ListView):
    """ Список сообщений, доступно для использования всем """

    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    """ Создание сообщения для рассылок """

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailings:message_list')


class MessageUpdateView(LoginRequiredMixin, PermissionRequiredMixin,
                        UpdateView):
    """ Редактирование сообщения для рассылок """

    model = Message
    form_class = MessageForm
    permission_required = 'mailings.change_message'
    success_url = reverse_lazy('mailings:message_list')


class MessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin,
                        DeleteView):
    """ Удаление сообщения для рассылок """

    model = Message
    permission_required = 'mailings.delete_message'
    success_url = reverse_lazy('mailings:message_list')


###############################################################################
class MailingLogListView(LoginRequiredMixin, ListView):
    """ Список логов по рассылке """

    model = Logs

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Logs.objects.filter(
            mailings=self.kwargs.get('pk')).order_by(
            '-last_try')
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailings'] = MailSettings.objects.get(
            pk=self.kwargs.get('pk'))
        return context_data

mailings/templates/mailings/base.html
<!doctype html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
</head>
<body>
{% include 'mailings/includes/inc_menu.html' %}

<div class="header">
    {% if request.path != '/' %}
    <p align="right"><a href="{% url 'mailings:home' %}" class="home-button">Главная
        страница </a>
    </p>
    {% endif %}
</div>

<div class="pricing-header text-center">
    <h1 class="display-4">SkyStore</h1>
    <p class="lead">SkyStore - это отличный вариант для организации email
        рассылок</p>
</div>

<body>
{% block content %}
{% endblock %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
        </div>

        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'blog:list' %}">Мы
                    пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'mailings:contacts'%}">Контакты</a>
                </li>
            </ul>
        </div>
    </div>
</footer>
<style>
    .card-text {
      overflow-wrap: break-word;
    }
</style>
</body>
</html>

mailings/templates/mailings/client_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить клиента {{object.first_name}}
                            {{object.last_name}} {{object.surname}}?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'mailings:clients' %}"
                           class="btn btn-primary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/client_form.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row justify-content-md-center" method="post"
          enctype="multipart/form-data">

        <div class="col-6">
            <div class="card mb-4">
                <div class="card-header">
                    <h3 class="card-title">
                        {% if object %}
                        Редактирование клиента
                        {% else %}
                        Добавление нового клиента
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-outline-success">
                        Сохранить
                    </button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>


    </form>
</div>

{% endblock %}

mailings/templates/mailings/client_list.html
{% extends 'mailings/base.html' %}


{% block content %}

<div class="container">
    <div class="col-12 mb-4">
        <h3 align="center" style="color:Black mb-4">Клиенты:</h3>
        <a class="btn btn-outline-primary"
           href="{% url 'mailings:client_create' %}">Добавить клиента</a>
    </div>

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header"></div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li> ФИО: {{object.first_name}}
                            {{object.last_name|first}}.{{object.surname|first}}.
                        </li>
                        <li>{{object.email}}</li>
                    </ul>
                    <br>
                    <div class="btn-group">
                        <a class="btn btn-outline-secondary"
                           href="{% url 'mailings:client_update' object.pk %}">Редактировать</a>
                        <a class="btn btn-outline-danger"
                           href="{% url 'mailings:client_delete' object.pk %}">Удалить</a>
                    </div>
                    <div class="card-footer m-2">
                        <p class="text-sm-start">Добавил клиента:
                            {{object.user|default:"-"}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

mailings/templates/mailings/contact.html
{% extends 'mailings/base.html' %}
{% block content %}
<h5 class="text-center">{{title}}</h5>
<br/>
<div class="row">
    <div class="col">
        <div class="card">
            <h5 class="card-title">Контакты:</h5>
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-15">Страна</td>
                        <td>Россия</td>
                    </tr>
                    <tr>
                        <td class="w-15">ИНН</td>
                        <td>7017086352</td>
                    </tr>
                    <tr>
                        <td class="w-15">Адрес</td>
                        <td>г.-к. Анапа, ул. Крымская 153</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card>">
            <h5 class="card-title">Оставить сообщение:</h5>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <button type="submit">Отправить</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

mailings/templates/mailings/index.html
<!doctype html>
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Всего рассылок в нашем
                        сервисе:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h1 class="text-center">{{ total_mailings_counter }}</h1>
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Количество активных
                        рассылок в нашем сервисе:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h1 class="text-center">{{ active_mailing_counter }}</h1>
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Количество уникальных
                        клиентов для рассылок:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h1 class="text-center">{{ unique_client_counter }}</h1>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <h3 align="center" style="color:Black mb-4">Кое-что из блога:</h3>

    {% for object in object_list %}


    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">"{{ object.title}}"</h4>
        </div>
        <div class="card-body">
            <p>{{ object.body | truncatechars:30}}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                </div>
            </div>
        </div>
        <div class="card-footer">
            Просмотры: {{ object.views_count }}
            <div class="d-flex justify-content-sm-end">
                <a href="{% url 'blog:view' object.pk %}"
                   class="btn btn-sm btn-outline-secondary"> Подробнее</a>
            </div>
        </div>

    </div>

    {% endfor %}

</div>
<div class="container">
    <div class="row">

        {% for object in random_blog %}

        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">"{{ object.title|title
                    }}" </h4>
            </div>
            <div class="card-body">
                <p>{{ object.body | truncatechars:100 }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    </div>
                </div>
            </div>
            <div class="card-footer">
                Добавлена: {{ object.date_create }}
                Просмотры: {{ object.views_count }}
                <div class="d-flex justify-content-sm-end">
                    <a href="{% url 'blog:view' object.pk %}"
                       class="btn btn-sm btn-outline-secondary"> Подробнее</a>
                </div>
            </div>

        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

</div>

mailings/templates/mailings/logs_list.html
{% extends 'mailings/base.html' %}


{% block content %}

<div class="row text-center">
    <table class="table table-striped-columns">
        <thead>
        <tr>
            <th scope="col">Статус</th>
            <th scope="col">Дата отправки</th>
            <th scope="col">Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list|dictsortreversed:"last_try" %}
        <tr>
            <td>{{ object.status }}</td>
            <td>{{ object.last_try }}</td>
            <td>{{ object.answer_server }}</td>
        </tr>
        </tbody>
        {% endfor %}
    </table>

</div>
{% endblock %}

mailings/templates/mailings/mailsettings_list.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="container">

    <div class="col-12 mb-4">
        <h3 align="center" style="color:Black mb-4">Рассылки:</h3>
    </div>
    <a class="btn btn-outline-primary mb-4"
       href="{% url 'mailings:message_create' %}">Создать сообщение для
        рассылки</a>
    {% if perms.mailings.add_mailsettings %}
    <a class="btn btn-outline-primary mb-4" href="{% url 'mailings:create' %}">Создать
        рассылку</a>
    {% endif %}
</div>

<div class="row text-center">
    {% for object in object_list %}
    <div class="col-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                Статус: {{object.get_status_display}}
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-4 mb-4 text-start m-3">
                    <li> {{object.start_time}} | {{object.end_time}}</li>
                    <li> Пользователь: {{object.user}}</li>
                    <li> {{object.message|truncatechars:60}}</li>
                </ul>
                <br>
                <div class="btn-group">
                    {% if perms.mailings.change_mailsettings %}
                    <a class="btn btn-outline-secondary"
                       href="{% url 'mailings:update' object.pk %}">Редактировать</a>
                    {% endif %}
                    {% if perms.mailings.delete_mailsettings %}
                    <a class="btn btn-outline-danger"
                       href="{% url 'mailings:delete' object.pk %}">Удалить</a>
                    {% endif %}
                    <a class="btn btn-outline-info"
                       href="{% url 'mailings:mail_log' object.pk %}">История</a>
                    {% if perms.mailings.set_status %}
                    <a class="btn btn-outline-info"
                       href="{% url 'mailings:status_update' object.pk %}">Изменить
                        статус</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>

{% endblock %}

mailings/templates/mailings/status_mailings.html
{% extends 'mailing/base.html' %}

{% block title %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="width: 95%;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2" style="display: flex; align-items: center;">
            User's mailing settings
        </h1>
    </div>
    {% endblock %}

    {% block content %}

    <div class="row text-center">
        <table class="table table-striped-columns">
            <thead>
            <tr>
                <th scope="col">PK</th>
                <th scope="col">Time</th>
                <th scope="col">Period</th>
                <th scope="col">Status</th>
                <th scope="col">Message</th>
                <th scope="col">Email / Name</th>
                <th scope="col">Owner</th>

                {% for object in object_list|dictsort:"user_id" %}
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">{{ object.pk }}</th>
                <td>{{ object.time }}</td>
                <td>{{ object.get_period_display }}</td>
                <td>
                    <a href="{% url 'mailing:users_mailing_settings_status_update' pk=object.pk %}">
                        {{ object.get_status_display }}</a>
                </td>
                <td style="word-wrap: break-word; max-width: 300px;">{{
                    object.message }}
                </td>
                <td style="word-wrap: break-word; max-width: 300px;">
                    {% for client in object.client.all %}
                    {{ client.email }} / {{ client.first_name }} {{
                    client.last_name }}<br>
                    {% endfor %}
                </td>
                <td>{{ object.user }}</td>
                {% endfor %}
            </tr>
            </tbody>
        </table>
    </div>
    {% endblock %}